### ISSUE TITLE
测试环境postman测试接口，报500 Internal Server Error

### ISSUE THREAD

**Issue by flyingfish123456** [DvcLAB/dockerhub#109]
接口：https://j.33.dvc/users
接口类型：GET
Authorization：
Type选择Bearer Token，
Token值为ey***rI76vurA

### 1.1 通过jps查看进程，DockerHubService没有启动
```
root@test01:~# jps
10041 Kafka
119946 Jps
93148 jboss-modules.jar
2686 QuorumPeerMain
```

### 1.2 启动方式
（用的是hub1上dockerhub-1.0.1.jar）
#### 1.2.1 nohup
root@test01:/opt/dockerhub-1.0.1# nohup java -jar lib/dockerhub-1.0.1.jar &
此时nohup.out日志：no main manifest attribute, in lib/dockerhub-1.0.1.jar

#### 1.2.2 shell
```
root@test01:/opt/dockerhub-1.0.1/bin# sh ./dockerhub
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'service_url'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at com.dvclab.dockerhub.DockerHubService.<init>(DockerHubService.java:53)
	at com.dvclab.dockerhub.DockerHubService.getInstance(DockerHubService.java:37)
	at com.dvclab.dockerhub.DockerHubService.main(DockerHubService.java:83)
```
#### 1.2.2 bat
```
root@test01:/opt/dockerhub-1.0.1/bin# ./dockerhub.bat 
./dockerhub.bat: line 1: $'@rem\r': command not found
./dockerhub.bat: line 2: @rem: command not found
./dockerhub.bat: line 3: $'@rem\r': command not found
./dockerhub.bat: line 4: syntax error near unexpected token `('
'/dockerhub.bat: line 4: `@rem Licensed under the Apache License, Version 2.0 (the "License");
```

## 2 疑问
jar包用的是hub1上dockerhub-1.0.1.jar，应该是没问题的。
不确定启动方式是哪里的问题？

**Comment by flyingfish123456** [comment]
docker 中openresty日志信息：
[error] 7#7: *61 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.7.12, server: ai.33.dvc, request: "GET /users HTTP/1.1", host: "ai.33.dvc

**Comment by flyingfish123456** [comment]
### 当前状态：服务可正常启动，但是接口仍然不通。

### 1. 分析过程：

1. 1. dockrhub日志：

```
root@test01:/opt/dockerhub-1.0.1/log# vi common.log 
2021-08-02 11:21:40.675 TRACE [main] [PooledDataSource:45] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:40.680 TRACE [main] [PooledDataSource:38] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:41.024 TRACE [main] [PooledDataSource:38] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:41.025 TRACE [main] [PooledDataSource:38] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:41.029 TRACE [main] [PooledDataSource:38] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:41.029 TRACE [main] [PooledDataSource:38] getDataSource - dockerhub --> max:20, busy:0
2021-08-02 11:21:41.058 INFO  [main] [Routes:55] init - Init routes ...
```

2. 1. openresty日志：

``10.0.7.12 - - [02/Aug/2021:11:50:54 +0000] "GET /users HTTP/1.1" 500 183 "-" "PostmanRuntime/7.28.2"`
`
### 2. 分析结果

 openresty请求转发失败

### 3.疑问
 对比了与hub1的配置，暂仍无法确定问题点？

**Comment by Scisaga** [comment]
参考 one.rewind.nio.web.route.Routes(line:68-70) 需要外部定义 UserCache 并初始化 Anthenticator
```
Caches.userCache = new UserCache(id -> User.getById(User.class, id), user -> user);

Authenticator authenticator = new Authenticator(Caches.userCache);
```

**Comment by youzi1030** [comment]
已解决
测试环境通过账号密码登录，导致缺少必要参数，报错java.lang.NullPointerException: null
解决方法见issue 111
