### ISSUE TITLE
测试环境发送请求报错，token verify error

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#111]
```
2021-08-06 07:08:31.441 INFO [qtp1376868499-30] [Routes:106] lambda$init$2 - [] [j.33.dvc] OPTIONS /hosts in 1ms
2021-08-06 07:08:31.503 ERROR[qtp1376868499-29] [Routes:91] lambda$init$1 - Token verify error, java.lang.NullPointerException: null
	at one.rewind.nio.web.filter.Authenticator.handle(Authenticator.java:75) ~[common-3.0.0.4.jar:?]
	at com.dvclab.dockerhub.route.Routes.lambda$init$1(Routes.java:88) [dockerhub-1.0.2.jar:?]
	at spark.FilterImpl$1.handle(FilterImpl.java:73) [spark-core-2.7.2.jar:?]
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:129) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by youzi1030** [comment]
原因：
由于生产环境登录部分是通过微信或github认证登录，头图的url参数等信息可直接使用微信或github的信息，而测试环境只能通过用户密码注册登录，缺少头图的url等信息，导致上述问题。

解决办法：

1. 通过KeyCloak配置默认头图的url参数。在groups下设置Attributes添加属性headimgurl，添加头图url。或给users下的user的Attributes下添加属性headimgurl。（采用）
2. 代码层面添加判断，设置默认参数。

**Comment by youzi1030** [comment]
原因：
由于生产环境登录部分是通过微信或github认证登录，头图的url参数等信息可直接使用微信或github的信息，而测试环境只能通过用户密码注册登录，缺少头图的url等信息，导致上述问题。

解决办法：
1. 通过KeyCloak配置默认头图的url参数。在groups下设置Attributes添加属性headimgurl，添加头图url。或给users下的user的Attributes下添加属性headimgurl。（采用）
2. 代码层面添加判断，设置默认参数。
