### ISSUE TITLE
测试环境 获取镜像列表时，报错java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#112]
```
2021-08-09 10:14:12.625 ERROR[qtp2055993975-45] [ImageRoute:104] lambda$static$5 - List Image error, uid[07fbc42a-d44a-402c-a5cc-ecc802b04ea1], java.lang.UnsupportedOperationException: null
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:72) ~[?:?]
	at java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:731) ~[?:?]
	at one.rewind.nio.http.Requester.req(Requester.java:505) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:472) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:446) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:384) ~[common-3.0.0.4.jar:?]
	at com.dvclab.dockerhub.route.ImageRoute.lambda$static$5(ImageRoute.java:58) [dockerhub-1.0.2.jar:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by youzi1030** [comment]
判断原因为：
com.dvclab.dockerhub.route.ImageRoute.java:58
Map.of()将数据转类型换为java.util.ImmutableCollections$MapN
导致后面put出问题
