### ISSUE TITLE
测试环境 获取镜像列表报错  req - Get input stream error code: 401

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#113]
```
2021-08-10 06:55:55.914 WARN [qtp1014035722-30] [Requester:550] req - Get input stream error code: 401, https://registry.33.dvc/v2/_catalog?n=10&last=
2021-08-10 06:55:55.914 TRACE[qtp1014035722-30] [Requester:137] decode - charset detected = UTF-8
2021-08-10 06:55:55.915 ERROR[qtp1014035722-30] [ImageRoute:105] lambda$static$5 - List Image error, uid[07fbc42a-d44a-402c-a5cc-ecc802b04ea1], org.codehaus.jettison.json.JSONException: JSONObject["repositories"] not found.
	at org.codehaus.jettison.json.JSONObject.get(JSONObject.java:360) ~[jettison-1.1.jar:1.1]
	at org.codehaus.jettison.json.JSONObject.getJSONArray(JSONObject.java:436) ~[jettison-1.1.jar:1.1]
	at com.dvclab.dockerhub.route.ImageRoute.lambda$static$5(ImageRoute.java:66) [dockerhub-1.0.2.jar:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by youzi1030** [comment]
docker registry配置出问题

**Comment by youzi1030** [comment]
## 问题1
### 问题分析
当使用指令去登录时
```
docker login registry.33.dvc -u ${username} -p ${password}
```
使用自签发泛域名证书会导致
```
x509: certificate signed by unknown authority
```
### 解决方法（ubuntu）

1. 首先确保生成的自签发ssl证书具有参数subjectAltName，例如：
```
openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key \
  -addext "subjectAltName = DNS:myregistry.domain.com" \
  -x509 -days 365 -out certs/domain.crt
```
2. 将证书（.crt或.pem文件）复制并重命名为ca.crt到 /etc/docker/certs.d/myregistrydomain.com:5000/ca.crt（无需重启Docker）
3. 若上述依然没解决问题，执行以下步骤
将证书（.crt文件，.pem文件不识别转为.crt文件）添加到/usr/local/share/ca-certificates/路径下
执行命令：
```
update-ca-certificates
service docker restart
```
参考：

- [Logging into your docker registry fails with x509 certificate signed by unknown authority error](https://www.ibm.com/docs/en/cloud-paks/cp-management/2.2.x?topic=tcnm-logging-into-your-docker-registry-fails-x509-certificate-signed-by-unknown-authority-error)
- [Use self-signed certificates](https://docs.docker.com/registry/insecure/)

## 问题2
### 问题分析
```
Error response from daemon: login attempt to https://registry.33.dvc/v2/ failed with status: 401 Unauthorized
```
### 解决方法

1. 登录KeyCloak，到如下界面
![docker-registry](https://user-images.githubusercontent.com/72690024/129010637-4b73854c-3f77-4280-93c2-0b63655a27e1.png)
点击download

2. 将文件夹中的localhost_trust_chain.pem文件添加至registry镜像配置文件下ssl文件中
![registry-token](https://user-images.githubusercontent.com/72690024/129011860-e7563023-fd93-4d6e-8066-9fcc5aebb694.png)
rootcertbundle------>localhost_trust_chain.pem
3. 启动Docker registry容器

参考：
[Configure a registry](https://docs.docker.com/registry/configuration/#token)
[Docker Authentication with Keycloak](https://developers.redhat.com/blog/2017/10/31/docker-authentication-keycloak#)
