### ISSUE TITLE
测试环境项目创建，从github获取项目信息失败

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#116]
```
2021-08-12 10:36:28.879 WARN [qtp1166616782-30] [Requester:624] handleRetry - one.rewind.nio.http.ReqObj@69a77296 retry exceeds limit
2021-08-12 10:36:28.880 WARN [qtp1166616782-30] [Requester:449] req - Error exec request, one.rewind.nio.distributor.exception.ProxyException$Timeout: Connection error
	at one.rewind.nio.http.Requester.decorateNetworkException(Requester.java:610) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:528) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.handleRetry(Requester.java:628) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:528) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.handleRetry(Requester.java:628) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:528) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.handleRetry(Requester.java:628) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:528) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:472) ~[common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:446) [common-3.0.0.4.jar:?]
	at one.rewind.nio.http.Requester.req(Requester.java:327) [common-3.0.0.4.jar:?]
	at com.dvclab.dockerhub.util.ResourceInfoFetcher.getProjectInfo(ResourceInfoFetcher.java:102) [dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.route.ProjectRoute.lambda$static$7(ProjectRoute.java:207) [dockerhub-1.0.2.jar:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:526) ~[?:?]
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:524) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:564) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
	at one.rewind.nio.http.Requester.req(Requester.java:523) ~[common-3.0.0.4.jar:?]
	... 32 more

2021-08-12 10:36:28.885 ERROR[qtp1166616782-30] [ProjectRoute:210] lambda$static$7 - Unable get Project info, url[https://github.com/DvcLAB/CNN], java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:148) ~[?:?]
	at com.dvclab.dockerhub.util.ResourceInfoFetcher.getProjectInfo(ResourceInfoFetcher.java:102) ~[dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.route.ProjectRoute.lambda$static$7(ProjectRoute.java:207) [dockerhub-1.0.2.jar:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by youzi1030** [comment]
解决方法：
对日本服务的tinyproxy进行配置

1. 更改/etc/tinyproxy/tinyproxy.conf
   * 添加字段    Allow ${测试环境ip}

2. 重启tinyproxy服务并查看服务状态
```
systemctl restart tinyproxy
systemctl status tinyproxy
```
3. 测试：在测试环境客户端
```
curl -x ${代理服务器ip}:${tinyproxy监听端口（默认为8888）} www.google.com
```
4. 测试成功后，中台代码配置代理服务
  * 修改ResourceInfoFetcher.conf配置文件，对如下字段进行修改
```
{
    "proxy_host": "${代理服务器地址}",
    "proxy_port": 8888
}
```
 * 修改PypiServerUpdater.conf文件，将ip地址、端口指向对应服务所在的服务器
