### ISSUE TITLE
获取用户S3的临时AK，SK和SessionToken报错

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#122]
```
2021-08-31 09:35:07.194 INFO [qtp1887854332-31] [S3Adapter:453] getS3CredentialWithKeycloak - 07fbc42a-d44a-402c-a5cc-ecc802b04ea1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazonaws.util.XpathUtils (file:/opt/dockerhub-1.0.2/lib/aws-java-sdk-core-1.11.934.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()
WARNING: Please consider reporting this to the maintainers of com.amazonaws.util.XpathUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-08-31 09:35:07.637 ERROR[qtp1887854332-31] [UserRoute:63] lambda$static$1 - List S3 tokens error, uid[07fbc42a-d44a-402c-a5cc-ecc802b04ea1], com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: null (Service: AWSSecurityTokenService; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.934.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1652) ~[aws-java-sdk-sts-1.11.934.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1619) ~[aws-java-sdk-sts-1.11.934.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1608) ~[aws-java-sdk-sts-1.11.934.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1002) ~[aws-java-sdk-sts-1.11.934.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:972) ~[aws-java-sdk-sts-1.11.934.jar:?]
	at one.rewind.db.S3Adapter.getS3CredentialWithKeycloak(S3Adapter.java:473) ~[common-3.0.2.jar:?]
	at com.dvclab.dockerhub.route.UserRoute.lambda$static$1(UserRoute.java:59) [dockerhub-1.0.2.jar:?]
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by youzi1030** [comment]
com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)

**Comment by youzi1030** [comment]
### 错误推断：使用错误的oidc_S3Access_trust_policy创建了角色，导致之后使用正确的oidc_S3Access_trust_policy创建角色时，此角色已经存在
radosgw-admin role list
```
{
        "RoleId": "61a48157-4d30-4dd3-8277-18ba93cdc148",
        "RoleName": "d4f2dc99-83e2-49ef-b0da-5e1ef03661d2",
        "Path": "/",
        "Arn": "arn:aws:iam:::role/d4f2dc99-83e2-49ef-b0da-5e1ef03661d2",
        "CreateDate": "2021-09-07T08:47:55.696Z",
        "MaxSessionDuration": 3600,
        "AssumeRolePolicyDocument": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Federated\":[\"arn:aws:iam:::oidc-provider/auth.33.dvc/auth/realms/DvcLAB\"]},\"Action\":[\"sts:AssumeRoleWithWebIdentity\"],\"Condition\":{\"StringEquals\":{\"auth.33.dvc/auth/realms/DvcLAB:app_id\":\"dvclab\",\"auth.33.dvc/auth/realms/DvcLAB:sub\":\"d4f2dc99-83e2-49ef-b0da-5e1ef03661d2\"}}}]}"
    }
```

oidc_S3Access_trust_policy
```
{
  "Version": "2012-10-17",
  "Statement":[
    {
      "Effect":"Allow",
      "Principal":{
        "Federated":[
          "arn:aws:iam:::oidc-provider/auth.dvclab.com/auth/realms/DvcLABTest01"
        ]
      },
      "Action":["sts:AssumeRoleWithWebIdentity"],
      "Condition":{
        "StringEquals":{
          "auth.dvclab.com/auth/realms/DvcLABTest01:app_id":"dvclab",
          "auth.dvclab.com/auth/realms/DvcLABTest01:sub":"keycloak_userid"
        }
      }
    }
  ]
}
```

**Comment by youzi1030** [comment]
### TODO
换回测试环境的keycloak，验证上述推断

**Comment by youzi1030** [comment]
在生产环境的keycloak中新建realm测试，可以正常获取临时的AK/SK和session token
换回测试环境的keycloak测试，依旧存在上述问题

**Comment by youzi1030** [comment]
在生产环境的keycloak中新建realm测试，可以正常获取临时的AK/SK和session token
换回测试环境的keycloak测试，依旧存在上述问题
