### ISSUE TITLE
dockerhub更新依赖commen版本至3.0.5时，启动失败

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/dockerhub#123]
```
2021-09-09 08:07:27.999 ERROR[main] [DockerHubService:79] run - INIT Failed, java.lang.NullPointerException: null
	at com.dvclab.dockerhub.model.Host.connectSshHost(Host.java:139) ~[dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.cache.HostCache.addHost(HostCache.java:48) ~[dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.cache.HostCache.init(HostCache.java:36) ~[dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.DockerHubService.run(DockerHubService.java:69) [dockerhub-1.0.2.jar:?]
	at com.dvclab.dockerhub.DockerHubService.main(DockerHubService.java:90) [dockerhub-1.0.2.jar:?]
```

**Comment by youzi1030** [comment]
### 问题分析
Host继承DockerHost，DockerHost中的成员变量ip、port、username、private_key、container_num缺少@DatabaseField注解，导致中台在获取host时，无法获取这些字段

**Comment by Scisaga** [comment]
更新依赖common版本至3.0.6.1
