### ISSUE TITLE
数据集添加的验证

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#59]
只有标准的s3数据集可以添加到数据集数据库中

**Comment by JJLAAA** [comment]
```
2021-04-23 20:56:35.914 ERROR[qtp1746332996-2005] [DatasetRoute:185] lambda$static$7 - Unable get Dataset info, url[https://s3.dvclab.com/chest-xray ], java.net.URISyntaxException: Illegal character in path at index 32: https://s3.dvclab.com/chest-xray /README.md
        at java.net.URI$Parser.fail(URI.java:2915) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3086) ~[?:?]
        at java.net.URI$Parser.parseHierarchical(URI.java:3168) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3116) ~[?:?]
        at java.net.URI.<init>(URI.java:600) ~[?:?]
        at one.rewind.io.requester.task.Task.<init>(Task.java:186) ~[common-2.0.9.16.jar:?]
        at one.rewind.io.requester.task.Task.<init>(Task.java:149) ~[common-2.0.9.16.jar:?]
        at one.rewind.io.requester.task.Task.<init>(Task.java:135) ~[common-2.0.9.16.jar:?]
        at one.rewind.io.requester.task.Task.<init>(Task.java:110) ~[common-2.0.9.16.jar:?]
        at one.rewind.io.requester.basic.BasicRequester.req(BasicRequester.java:310) ~[common-2.0.9.16.jar:?]
        at com.dvclab.dockerhub.util.ResourceInfoFetcher.getDatasetInfo(ResourceInfoFetcher.java:127) ~[dockerhub-1.0.1.jar:?]
        at com.dvclab.dockerhub.route.DatasetRoute.lambda$static$7(DatasetRoute.java:182) [dockerhub-1.0.1.jar:?]
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) [spark-core-2.7.2.jar:?]
        at spark.http.matching.Routes.execute(Routes.java:61) [spark-core-2.7.2.jar:?]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [spark-core-2.7.2.jar:?]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-core-2.7.2.jar:?]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.Server.handle(Server.java:530) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [jetty-server-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [jetty-util-9.4.8.v20171121.jar:9.4.8.v20171121]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by JJLAAA** [comment]
解决办法：在`/datasets_info`接口中添加url的格式验证
待验证
