### ISSUE TITLE
Kafka解析 Header错误导致出现空指针异常

### ISSUE THREAD

**Issue by JJLAAA** [DvcLAB/dockerhub#9]
- 错误定位：common 包中 one.rewind.db.kafka.KafkaClient 526行
```java
String clientAddress = new String(record.headers().lastHeader(ClientAddress).value());
```
- 推测是因为producer产生消息时并没有添加`client.address`这个头，但是[查询](https://stackoverflow.com/questions/58716683/is-there-a-way-to-add-headers-in-kafka-console-producer-sh)得知producer.sh并不能加自定义的Header，需要使用[kafkacat](https://github.com/edenhill/kafkacat)等其他工具
- 根据[how to view kafka headers](https://stackoverflow.com/questions/55180620/how-to-view-kafka-headers/55182021)测试得到确实没有携带Headers

**Comment by Scisaga** [comment]
拟改为：
```
String clientAddress = "";
if(record.headers().lastHeader(ClientAddress) != null) {
	clientAddress = new String(record.headers().lastHeader(ClientAddress).value());
}

callback.call(record.key(), record.value(), clientAddress);
```

**Comment by Scisaga** [comment]
compile 'one.rewind:raw-data:2.0.9.*' --> compile 'one.rewind:raw-data:2.0.9.12'

**Comment by JJLAAA** [comment]
![image](https://user-images.githubusercontent.com/47405525/112484520-fd67cc80-8db4-11eb-9d38-f340eaad2ef1.png)

**Comment by JJLAAA** [comment]
- `com.esotericsoftware.kryo.util.DefaultClassResolver`
```java
  public Registration readClass (Input input) {
      int classID = input.readVarInt(true);
      switch (classID) {
      case Kryo.NULL:
	      if (TRACE || (DEBUG && kryo.getDepth() == 1)) log("Read", null);
	      return null;
      case NAME + 2: // Offset for NAME and NULL.
	      return readName(input);
      }
      if (classID == memoizedClassId) return memoizedClassIdValue;
      // 需要注册，但是并未注册
      // 不强制注册
      Registration registration = idToRegistration.get(classID - 2);
      if (registration == null) throw new KryoException("Encountered unregistered class ID: " + (classID - 2));
      if (TRACE) trace("kryo", "Read class " + (classID - 2) + ": " + className(registration.getType()));
      memoizedClassId = classID;
      memoizedClassIdValue = registration;
      return registration;
  }
```··

**Comment by JJLAAA** [comment]
- 报错信息
```
2021-03-27 14:39:51.359 ERROR[KafkaClient-C000-1] [KafkaClient$Operator:551] lambda$run$2 - Error, java.lang.ClassCastException: class java.lang.String cannot be cast to class one.rewind.db.kafka.Msg (java.lang.String is in module java.base of loader 'bootstrap'; one.rewind.db.kafka.Msg is in unnamed module of loader 'app')
at one.rewind.db.kafka.KafkaClient$Operator.lambda$run$2(KafkaClient.java:548) [common-2.0.9.14.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
- common 项目`one.rewind.db.kafka.KafkaClient` 
- Msg与String类型不兼容
```java
ConsumerRecords<String, Msg> records = consumer.poll(100L);

if (records != null && records.count() > 0) {

logger.info("Partition:[{}], Records:{}", records.partitions().stream().map(p->String.valueOf(p.partition())).collect(Collectors.joining(", ")), records.count());

for (ConsumerRecord<String, Msg> record : records) {

	  if (callbackList != null && callbackList.size() > 0) {
  
		  executor.submit(()->{
  
			  try {
				  for (ReceiveCallback callback : callbackList) {
  
					  String clientAddress = "";
					  if(record.headers().lastHeader(ClientAddress) != null) {
						  clientAddress = new String(record.headers().lastHeader(ClientAddress).value());
					  }
  
					  callback.call(record.key(), record.value(), clientAddress);
				  }
			  } catch (Throwable t) {
				  logger.error("Error, ", t);
			  }
		  });
	  }
  }
}
```
@Scisaga

**Comment by Scisaga** [comment]
common项目中增加了MsgStringSerializer，并优化了KafkaClient相关配置方法，common依赖 => 2.0.9.16
