### ISSUE TITLE
测试Ceph S3 泛域名支持情况

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/dockerhub#98]
无法通过三级域名访问bucket，错误信息
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: test-bucket.s3.dvclab.com

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5194)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1119)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1051)
	at one.rewind.db.S3Adapter.createBucket(S3Adapter.java:209)
	at one.rewind.db.s3.test.AssumeRoleWithWebIdentityTest.createBucket1(AssumeRoleWithWebIdentityTest.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.net.UnknownHostException: test-bucket.s3.dvclab.com
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy22.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1331)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 36 more
```

**Comment by linstein** [comment]
配置了泛域名的HTTPS访问，并修复s3.dvclab.com的导向问题，但目前运行测试用例`testCreateBucket()`时出现以下错误
```
com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: tx000000000000000000172-0060ddaac1-37c3-xian; S3 Extended Request ID: 37c3-xian-default; Proxy: null)
, S3 Extended Request ID: 37c3-xian-default
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5194)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1119)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1051)
	at one.rewind.db.s3.test.S3AdapterTest.testCreateBucket(S3AdapterTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by linstein** [comment]
1. 查看了Ceph网关的日志，发现执行的放入文件操作没有任何记录，日志结果如下：
```
{
    "bucket_id": "cdd2a1a0-b7aa-4a4e-b5e5-158c3eb78067.14275.2",
    "bucket_owner": "rr",
    "bucket": "test",
    "log_entries": [
        {
            "bucket": "test",
            "time": "2021-07-05T08:36:29.707988Z",
            "time_local": "2021-07-05T08:36:29.707988+0000",
            "remote_addr": "10.0.7.13",
            "user": "rr",
            "operation": "create_bucket",
            "uri": "PUT /test/ HTTP/1.1",
            "http_status": "200",
            "error_code": "",
            "bytes_sent": 866,
            "bytes_received": 0,
            "object_size": 0,
            "total_time": 83,
            "user_agent": "aws-sdk-java/1.11.934 Windows_10/10.0 Java_HotSpot(TM)_64-Bit_Server_VM/11.0.11+9-LTS-1
            "referrer": "",
            "trans_id": "tx00000000000000000002b-0060e2c48d-37c1-xian"
        },
        {
            "bucket": "test",
            "time": "2021-07-05T08:36:29.951986Z",
            "time_local": "2021-07-05T08:36:29.951986+0000",
            "remote_addr": "10.0.7.13",
            "user": "rr",
            "operation": "create_bucket",
            "uri": "PUT /test/ HTTP/1.1",
            "http_status": "200",
            "error_code": "",
            "bytes_sent": 866,
            "bytes_received": 0,
            "object_size": 0,
            "total_time": 131,
            "user_agent": "aws-sdk-java/1.11.934 Windows_10/10.0 Java_HotSpot(TM)_64-Bit_Server_VM/11.0.11+9-LTS-1
            "referrer": "",
            "trans_id": "tx00000000000000000002c-0060e2c48d-37c1-xian"
        }
    ],
    "log_sum": {
        "bytes_sent": 1732,
        "bytes_received": 0,
        "total_time": 214,
        "total_entries": 2
    }
}
```

2. 使用S3 的Python SDK进行创建bucket的操作，发现可以执行，bucket创建成功；但它使用的是 s3.dvclab.com/${bucket_name}的形式进行api请求

**Comment by linstein** [comment]
1. 翻看s3文档，发现Java API可以选择使用泛域名和绝对路径两种使用方式，目前将Java项目了的访问方式修改为 s3.dvclab.com/${bucket_name}的格式后即可访问
2. 修改访问方式代码如下
```
s3 = AmazonS3ClientBuilder.standard()
				.withCredentials(credentialsProvider)
				.withEndpointConfiguration(endpointConfiguration)
				.withPathStyleAccessEnabled(true)
				.build();
```
参考：
    1. [Method Not allowed in S3](https://stackoverflow.com/questions/57174685/method-not-allowed-in-s3)
    2. [在Java SDK Amazon S3中配置路径样式](https://www.coder.work/article/860426)

**Comment by linstein** [comment]
### 问题2
换为如上访问方式的时候，直接执行会报错
```
com.amazonaws.services.s3.model.AmazonS3Exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: tx000000000000000000062-0060e41fa9-381f-xian; S3 Extended Request ID: 381f-xian-default; Proxy: null)
, S3 Extended Request ID: 381f-xian-default
```

### 解决2
将region参数设置为 us-east-1
参考：
    1. [Java aws sdk - The specified location-constraint is not valid (non-amazon)](https://stackoverflow.com/questions/47769300/java-aws-sdk-the-specified-location-constraint-is-not-valid-non-amazon)
